#!/bin/bash
SOURCES="/usr/local/etc/blacklist.src"
BASEDIR="/usr/local/"

ret()
{
	wget -qqq "$1" -O- >> $LIST
}

filt_ret()
{
	wget -qqq "$1" -O- | sed "$2" >> $LIST
}

update()
{
	LIST=`mktemp`
	SORT=`mktemp`
	echo "Updating Sources..."
	wget -qqq https://raw.githubusercontent.com/halitalf/blacklist/master/etc/blacklist.src -O $SOURCES
	. $SOURCES
	echo "Filtering IPs..."
	cat $LIST|sort -V|uniq > $SORT
	IPAS=`cat $SORT|wc -l`
	CIPA=1
	echo "Adding Rules..."
	echo -n "Banning IPs: 1 of $IPAS"
	for IP in `cat $SORT`
	do
		ufw deny from $IP to any &>/dev/null
		CIPA=$((CIPA+1))
		echo -en "\e[0K\rBanning IPs: $CIPA of $IPAS"
		sleep 0.1
	done
	echo "Reloading Firewall..."
	ufw reload &>/dev/null
	echo "Cleaning Up..."
	rm $LIST &>/dev/null
	rm $SORT &>/dev/null
}

upgrade()
{
	echo "Initializing..."
	cd /usr/local
	git init &>/dev/null
	echo "Checking Remote..."
	git remote add origin https://github.com/halitalf/blacklist.git &>/dev/null
	echo "Fetching Updates..."
	git fetch --all &>/dev/null
	git reset --hard origin/master &>/dev/null
	echo "Finishing Up..."
	git checkout -t origin/master &>/dev/null
	chmod a+x /usr/local/sbin/blacklist &>/dev/null
	echo "Cleaning Up..."
	rm -fr .git* &>/dev/null
}

case $1 in
	upgrade)
		upgrade
		;;
	update)
		update
		;;
	*)
		echo "Unknown Command"
		;;
esac